### PR TITLE
fix(career-form): resolve file-dropper issues

### LINKED ISSUE #346: Career Form Upload Issues
1. Can't handle files with `,` in the file name
Edit: The minimal file name is :`,.pdf` which is valid on osx.
I have not checked the code but it's weird. If you have a file with the name `a (b, c).pdf` and you select or drop it into the file upload it throws an exception. See me screen record. You can easily create such a file with `touch "a (b, c).pdf"` and upload that empty file as we don't check the file content here.

It works for other files as expected. I had a real file and I just condensed the error down to this format.
https://user-images.githubusercontent.com/1701755/152187171-5c05000a-ffa9-4461-bcf7-eb0a417c269a.mp4

See https://github.com/satellytes/satellytes.com/pull/347 for a working fix, although I don't know if that has side effect.

2. Missing error key `career.error.message`
3. Drop is working but the validation doesn't respect the dropped file so you can't proceed.

Feel free to test the form submission as much as you want to fix the form 🙏

### PR DESCRIPTION
**Pull request by hofmann-felix**
**What's included?**
- When the user uploads a file via drop, he gets an error when submitting the form, although the file was uploaded correctly. This problem has been fixed
- The cover letter field shows the correct error message now
- upload form accept names with special chars now (cherry picked from https://github.com/satellytes/satellytes.com/pull/347) 

**Why WIP?**
- The changes still need to be tested

### CODE REVIEW

File: src/components/pages/career-details/career-form/career-form.tsx [hunk 1]
```diff
@@ -131,7 +131,22 @@ export const CareerForm: React.FC<CareerFormProps> = (props) => {
...
+
   const onSubmit = async (formValues: RawFormData): Promise<void> => {
+    if (selectedFiles?.length === 0) {
+      setError(
+        'documents',
+        { type: 'manual', message: t<string>('career.error.cv') },
+        { shouldFocus: true },
+      );
+      return;
+    }
```
Comment (georgiee) [inline src/components/pages/career-details/career-form/career-form.tsx:149]: nice how you resolved the required error handling

**Comment by feedm3** [comment]
I hardened the filename parsing and fixed a broken translation key. Code looks good for me now, but I couldn't check the upload on the deployed branch as the Personio API blocks the gtsb.io domain.

I will approve it, but before we merge we need to make sure to have a proper test of the upload.

**Review by feedm3 — APPROVED** [review]

**Comment by georgiee** [comment]
We just checked the code and it's not CORS. It's a weird API response. The Personio API is shitty and answers a missing category with a 500 error. This means we introduced an error by not sending the correct payload as before:

Before:
```
-----------------------------254277083419422831133375352450
Content-Disposition: form-data; name="categorised_documents[0][category]"

cv
-----------------------------254277083419422831133375352450
Content-Disposition: form-data; name="category_select"

[object Object]
```


After:

```
-----------------------------24917449282118928490734399228
Content-Disposition: form-data; name="categorised_documents[0][category]"

undefined
-----------------------------24917449282118928490734399228
Content-Disposition: form-data; name="category_select"

[object Object]
-----------------
```

that's the documentation (FYI)
https://developer.personio.de/reference#post_v1-recruiting-applications-documents

**Comment by georgiee** [comment]
I pushed the necessary change to make it finally work. We have collected quite some technical debt in that upload form which makes it quite some duty to update things 🤓

File: src/components/legacy/icons/form-icons/clear.tsx [hunk 2]
```diff
@@ -10,13 +10,13 @@ export const Clear = () => (
   >
     <path
       d="M1 1L11 11"
-      stroke="#ffffff"
+      stroke="currentColor"
```
Comment (georgiee) [inline src/components/legacy/icons/form-icons/clear.tsx:13]: The white colors of the close x to remove a file was almost not readable
Screen Shot 2022-02-04 at 15 59 57
Screen Shot 2022-02-04 at 16 01 14

File: src/components/pages/career-details/career-form/career-components.tsx [hunk 3]
```diff
@@ -109,12 +109,14 @@ export const Actions = ({
...
       <>
         <FormError error={error} />
-        <Trans i18nKey={'career.again-text'}>
+        <br />
+        <Trans i18nKey={'career.action.again-text'}>
           Versuch es bitte noch einmal. Klappt es nicht dann schicke deine
           Bewerbung direkt an <strong>career@satellytes.com</strong>
         </Trans>
+        <br />
         <SendButton onClick={() => tryAgainFn()}>
```
Comment (georgiee) [inline src/components/pages/career-details/career-form/career-components.tsx:118]: this fixes the layout a little bit at least when an error is displayed.
Screen Shot 2022-02-04 at 16 02 03

File: src/components/pages/career-details/career-form/career-form.tsx [hunk 4]
```diff
@@ -159,8 +175,8 @@ export const CareerForm: React.FC<CareerFormProps> = (props) => {
       if (key === 'documents') {
         for (let i = 0; i < formValues.documents.length; i++) {
           const keyName = `categorised_documents[${i}][file]`;
-          const fileName = formValues.documents[i].name.split('.')[0];
-          const category = formValues.category_select[fileName];
+          const fileId = createFileId(formValues.documents[i].name);
```
Comment (georgiee) [inline src/components/pages/career-details/career-form/career-form.tsx:178]: we need to access the category select by the correct accessor. We changed the file name to a file id where the category select is build but we forget to change it here. Hence we had some undefined which caused the 500.

Her instead of `a_b` (the new file id way of naming things) we still tried to use `a,b` to access the related category. 
Screen Shot 2022-02-04 at 15 44 48

Of course all of that will fall apart if people upload files that result in conflicting file ids like `a,b` vs `a b` as both will get file ids to `a_b` but to be honest, it's an edge case and it's a mess in there so I think it's good enough right now.

File: src/components/pages/career-details/career-form/utils.ts [hunk 5]
```diff
@@ -0,0 +1,19 @@
+const getFilenameWithoutFiletype = (filename) => {
```
Comment (georgiee) [inline src/components/pages/career-details/career-form/utils.ts:1]: we don't need to expose it, the fileId function is what we are interested in. so it stays local.

**Review by georgiee — APPROVED** [review]
Works now ✨ Thanks everyone involved. Let's merge once green on behalf of @hofmann-felix who did the ground work for the PR 🙌
