### PR TITLE
fix: footer design issues

### LINKED ISSUE #475: Design: Quick fix footer
Thanks for updating the language dropdown in the footer. Please fix two more things:

* English/Deutsch should be right-aligned with the lines below.
* Social Icons in black please and hover in white.

EricsShot 2022-03-08 09 37 46

### PR DESCRIPTION
**Pull request by hofmann-felix**
Resolves: #475 
Preview URL: https://satellytescommain21751-fixfooterdesignissues.gtsb.io/

**What's included?**
* social icons are black (on hover white) now
* the colors of the footer are imported from `theme.tsx`
* the language switch is aligned right now

**Preview:**
Bildschirmfoto 2022-03-08 um 16 56 48

### CODE REVIEW

**Comment by ghost** [comment]
# [Gatsby Cloud](https://www.gatsbyjs.com) Build Report
**satellytes.com-main**

:tada: Your build was successful! [See the Deploy preview here.](https://satellytescommain21751-fixfooterdesignissues.gtsb.io)

## Build Details

[View the build logs here.](https://gatsbyjs.com/dashboard/f215130d-15e3-4176-9252-e13166fe48de/sites/674be368-adf0-4ac5-8fae-f9a4493adc51/builds/ff1f203b-d31d-488c-8c13-ca8536b70ae2/details)

:clock1: Build time: **1m**

## Performance

### Lighthouse report

| Metric | Score |
| ----- | ---- |
| Performance |   :large_orange_diamond: 70   |
| Accessibility |   :green_heart: 97   |
| Best Practices |   :green_heart: 100   |
| SEO |   :large_orange_diamond: 79   |

:link: [View full report](https://build-ff1f203b-d31d-488c-8c13-ca8536b70ae2.gtsb.io/reports/lighthouse/index.html)

File: src/components/layout/navigation/navigation.tsx [hunk 1]
```diff
@@ -185,17 +198,16 @@ const SiteNavigationLink = styled(Link)<{ $isSelected: boolean }>`
...
-    color: #ffffff;
+    color: ${theme.palette.text.defaultLight};
   }
 `;
 
 const IconWrapper = styled.div`
-  color: white;
-  transition: all 0.2s ease-in;
-  opacity: 0.3;
+  color: ${theme.palette.text.default};
```
Comment (georgiee) [inline src/components/layout/navigation/navigation.tsx:206]: much better black than opacity. Thanks.

File: src/components/layout/navigation/navigation.tsx [hunk 2]
```diff
@@ -168,14 +175,20 @@ const SiteNavigationLink = styled(Link)<{ $isSelected: boolean }>`
   ${TextStyles.menuItemS}
 
   text-decoration: none;
-  color: ${(props) => (props.$isSelected ? '#ffffff' : '#202840')};
+  color: ${(props) =>
```
Comment (georgiee) [inline src/components/layout/navigation/navigation.tsx:178]: 👍for the theming references

File: src/components/layout/header/language-switch.tsx [hunk 3]
```diff
@@ -25,15 +25,18 @@ const StyledSelection = styled.select`
...
   cursor: pointer;
 `;
 
-export const StyledChevron = styled(Icon)`
+export const StyledChevron = styled(Icon)<{ isEnglish: boolean }>`
   cursor: pointer;
-  /*margin-right: -22px makes the Chevron clickable*/
-  margin-right: -22px;
+  /*margin-right: negative margin makes the Chevron clickable*/
+  margin-right: ${(props) => (props.isEnglish ? '-26px' : '-22px')};
```
Comment (georgiee) [inline src/components/layout/header/language-switch.tsx:39]: so many magic numbers and in addition it's a different number per language 😳 Is that such a big issue here or what's happening?

File: src/components/layout/header/language-switch.tsx [hunk 4]
```diff
@@ -25,15 +25,18 @@ const StyledSelection = styled.select`
 
   color: inherit;
   padding-left: 18px;
+  text-align: right;
+  /*"direction: rlt" aligns the text right in Safari*/
+  direction: rtl;
```
Comment (georgiee) [inline src/components/layout/header/language-switch.tsx:30]: This looks hacky and when I disable them I see minimal changes but for sure not what I would expect when dealing with `direction` and `rtl`. I'm sure there is a better solution. Can you speak about your general issues you had here?

**Review by georgiee — CHANGES_REQUESTED** [review]
Thanks, that looks good. I have one blocker regarding the language switch changes. Maybe we can talk about that before merging it.

File: src/components/layout/header/language-switch.tsx (hunk 3 above)
Comment (hofmann-felix) [reply src/components/layout/header/language-switch.tsx:39]: I don't think this line is ideal, but I couldn't think of a better solution. Maybe you have an idea.
The problem is that the `<select>` item has the width of the widest option. Without this distinction the distance between the chevron and the text would change depending on the language because of the `text-align: right` (s. screenshot)
Bildschirmfoto 2022-03-10 um 08 01 11
Bildschirmfoto 2022-03-10 um 08 01 21

File: src/components/layout/header/language-switch.tsx (hunk 4 above)
Comment (hofmann-felix) [reply src/components/layout/header/language-switch.tsx:30]: The problem is that the `text-align: right` doesn't work in Safari. I did a quick research and found the solution with `direction`, which would work here.

Screenshot without `direction: rtl` in Safari
Bildschirmfoto 2022-03-10 um 08 12 00

**Comment by georgiee** [comment]
I will try to find some time to help investigating. I will provide an alternative or approve 🙌

**Review by georgiee — APPROVED** [review]

**Comment by georgiee** [comment]
I just approved without going into details. Thanks for putting in so much effort into fixing this small issue. It's good as is 👍
