### PR TITLE
fix: add image to blog content

### LINKED ISSUE #335: RSS feed is missing some images
Some images are either missing or have a broken URL in the RSS feed. They are not visible in Feedly:

Screenshot 2022-01-21 at 14 26 19

Haven't looked into it, but it has something to do with the rss.xml we create.

### PR DESCRIPTION
**Pull request by feedm3**
Feedly parses the content of a blog post to extract the image. Some blog posts don't have an image in the content, so I added the title image right at the start of the content. Looks very cool in Feedly.

I'm not sure how other feed readers behave. The RSS standard doesn't have a simple image attribute for an item. I assume that they behave similarly. The popular [Golem RSS](https://rss.golem.de/rss.php?feed=RSS2.0) feed does it the same way.

<details>
<summary>Screenshot of the blog summary</summary>
Screenshot 2022-01-25 at 08 09 39
</details>

<details>
<summary>Screenshot of the blog posts overview</summary>
Screenshot 2022-01-25 at 08 10 19

</details>

<details>
<summary>Screenshot of a blog post</summary>
Screenshot 2022-01-25 at 08 03 56
</details>

I also changed the Satellytes slogan in our `gatsby-config.js` to English, as this is the default language.

Fixes #335

### CODE REVIEW

File: gatsby-config.js [hunk 1]
```diff
@@ -29,12 +29,13 @@ const SEO_EXCLUDED_URLS = [
...
 
 const RSS_FEED_URL = '/blog/rss.xml';
+const DEFAULT_META_IMAGE_URL_PATH = '/sy-share-image.jpg';
 
 module.exports = {
   siteMetadata: {
     title: 'Satellytes',
     description:
-      'Satellytes ist eine Digital-Agentur, die um große Unternehmen kreist und ihnen bei der Transformation und Optimierung digitaler Services und Interfaces hilft.',
+      'Passionate experts that strive to build the best possible and above all right solution for our clients and customers.',
```
Comment (georgiee) [inline gatsby-config.js:38]: 👍

File: gatsby-config.js [hunk 2]
```diff
@@ -130,14 +130,25 @@ module.exports = {
...
+                    title: blogPostMeta.title,
+                    site_url: site.siteMetadata.siteUrl,
+                    date: blogPostMeta.date,
                     description: edge.node.excerpt,
-                    date: edge.node.frontmatter.date,
-                    url: site.siteMetadata.siteUrl + edge.node.frontmatter.path,
-                    guid:
-                      site.siteMetadata.siteUrl + edge.node.frontmatter.path,
-                    custom_elements: [{ 'content:encoded': edge.node.html }],
-                  });
```
Comment (georgiee) [inline gatsby-config.js:140]: Asking because it looks similar: Did something change here or is this only due to the introduction of the `blogPostMeta` refactoring ?

File: gatsby-config.js [hunk 3]
```diff
@@ -149,11 +160,20 @@ module.exports = {
...
                       frontmatter {
                         title
                         date
                         path
+                        shareImage: featuredImage {
+                          childImageSharp {
+                            fixed(width: 1440, height: 760) {
+                              src
+                            }
+                          }
```
Comment (georgiee) [inline gatsby-config.js:175]: great, thanks for pulling in the share image

File: gatsby-config.js [hunk 4]
```diff
@@ -130,14 +130,25 @@ module.exports = {
...
-                    url: site.siteMetadata.siteUrl + edge.node.frontmatter.path,
-                    guid:
-                      site.siteMetadata.siteUrl + edge.node.frontmatter.path,
-                    custom_elements: [{ 'content:encoded': edge.node.html }],
-                  });
+                    url: site.siteMetadata.siteUrl + blogPostMeta.path,
+                    guid: site.siteMetadata.siteUrl + blogPostMeta.path,
+                    custom_elements: [
+                      {
+                        'content:encoded': `<img src='${imageUrl}' alt=''/> ${edge.node.html}`,
```
Comment (georgiee) [inline gatsby-config.js:148]: smart 🤓🙌

**Review by georgiee — APPROVED** [review]
Let's try this. Thanks!

One thing, my feedly feed seems to be cached as I don't get the same results as you for the preview url. But you proofed it with your own screenshots so I'm good with that. Thanks.

Screen Shot 2022-01-25 at 09 02 43

File: gatsby-config.js (hunk 2 above)
Comment (feedm3) [reply gatsby-config.js:140]: Only because of the variable name change.
