### PR TITLE
fix: accordion design issues

### LINKED ISSUE #354: Design: Accordions
Please fix the lineheight, it should be 150%.

On mobile make the left and right page margin 0 for the accordions, so the lines start at 0% and 100% width. This way we have more width for the textblocks also. See Figma.

### PR DESCRIPTION
**Pull request by hofmann-felix**
Resolves: https://github.com/satellytes/satellytes.com/issues/354
Preview URL: https://satellytescommain21751-fixaccordionlayout.gtsb.io/career/

**What's included?**
- On mobile, the career accordion has no left/right margin now
- The `Text R` font style is applied to the accordion text 

Bildschirmfoto 2022-02-08 um 14 45 51

### CODE REVIEW

File: src/components/pages/career/application-process.tsx [hunk 1]
```diff
@@ -3,11 +3,25 @@ import { Accordion, AccordionSection } from '../../ui/accordion/accordion';
...
+const AccordionWrapper = styled.div`
+  margin: 0 -24px;
+
+  ${up('sm')} {
+    margin: 0;
+  }
+`;
+
+const AccordionText = styled.p`
+  ${TextStyles.textR}
```
Comment (georgiee) [inline src/components/pages/career/application-process.tsx:22]: 👍

**Review by georgiee — APPROVED** [review]
Before/After looks great, thanks for that!
Screen Shot 2022-02-09 at 09 27 38
Screen Shot 2022-02-09 at 09 27 40


Technically the designers should approve the PRs too, shouldn't they 🤔 (@esreverse ?)
Anyway this one looks great, thanks!

**Comment by georgiee** [comment]
Eric provided some additions to handle, see:
https://github.com/satellytes/satellytes.com/issues/354#issuecomment-1033488913

**Comment by feedm3** [comment]
Looks good right now and fit's the requirements. Will merge it. Thanks :)
