### PR TITLE
fix: adjust spacing in blog articles

### LINKED ISSUE #437: Design: Spacings in blog articles too little
EricsShot 2022-02-22 11 39 38

Whitespace/Spacings between content blocks (image with caption <> text, text <> text, text <> new paragraph) look very dense, see screenshot. Spacings between all of the content blocks should be 48 px and above new headlines 80 px. see Figma: https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3705%3A29422

With more whitespace, the text gets a better visual rhythm and grouping.

### PR DESCRIPTION
**Pull request by hofmann-felix**
Resolves: #437 
Preview URL: https://satellytescommain21751-fixspacingblog.gtsb.io/blog/

Approved by the design team ✔️

### What's included?
* The spacing between the content blocks of a blog post is adjusted according to the following rules:
  * **Headlines**: `margin-top: 80px` and `margin-bottom: 16px`
  * **Non Text Content Blocks** (e.g. images, code snippets): `margin-top` and `margin-bottom 48px`
  * **Text Content Blocks**: `margin-top` and `margin-bottom 16px`
* Some minor changes on the career details page because it is reusing some of the blog components
 
### Preview
Bildschirmfoto 2022-03-08 um 17 11 30

### CODE REVIEW

File: src/components/legacy/markdown/custom-components.tsx [hunk 1]
```diff
@@ -143,13 +128,13 @@ const customSatellytesComponents = {
...
-    return <SubTitleCondensed as={'h1'}>{props.children}</SubTitleCondensed>;
+    return <SubTitle as={'h1'}>{props.children}</SubTitle>;
   },
   h2(props) {
-    return <SubTitleCondensed as={'h2'}>{props.children}</SubTitleCondensed>;
+    return <SubTitle as={'h2'}>{props.children}</SubTitle>;
   },
   h3(props) {
-    return <TextTitleCondensed as={'h3'}>{props.children}</TextTitleCondensed>;
+    return <TextTitle as={'h3'}>{props.children}</TextTitle>;
```
Comment (georgiee) [inline src/components/legacy/markdown/custom-components.tsx:137]: 👍

**Review by georgiee — APPROVED** [review]
Thanks for managing those changes. Looks good and I see the design approval. Thanks!
I think  the more you work on those detail the more it make sense to refactor the last bits of the page (try to remove the legacy folder mostly). I'm thankful that you work on those small bits! Let's merge this.
